---
# Install Flatpak applications, default to Flathub repository

- name: Flatpak - Enable Flathub repository
  become: yes
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  tags:
    - flatpak

- name: Install Anki (Flatpak)
  flatpak:
    name: net.ankiweb.Anki
    method: system
  tags:
    - flatpak

- name: Install Calibre (Flatpak)
  flatpak:
    name: com.calibre_ebook.calibre
    method: system
  tags:
    - flatpak

- name: Install Celluloid (Flatpak)
  flatpak:
    name: io.github.celluloid_player.Celluloid
    method: system
  tags:
    - flatpak

- name: Install Chromium (Flatpak)
  flatpak:
    name: org.chromium.Chromium
    method: system
  tags:
    - flatpak

- name: Install Dconf-Editor (Flatpak)
  flatpak:
    name: ca.desrt.dconf-editor
    method: system
  tags:
    - flatpak

- name: Install EasyTAG (Flatpak)
  flatpak:
    name: org.gnome.EasyTAG
    method: system
  tags:
    - flatpak

- name: Install Fedora Media Writer (Flatpak)
  flatpak:
    name: org.fedoraproject.MediaWriter
    method: system
  tags:
    - flatpak

- name: Install Flatseal (Flatpak)
  flatpak:
    name: com.github.tchx84.Flatseal
    method: system
  tags:
    - flatpak

- name: Install FontManager (Flatpak)
  flatpak:
    name: org.gnome.FontManager
    method: system
  tags:
    - flatpak

- name: Install GIMP (Flatpak)
  flatpak:
    name: org.gimp.GIMP
    method: system
  tags:
    - flatpak

- name: Install Geary (Flatpak)
  flatpak:
    name: org.gnome.Geary
    method: system
  tags:
    - flatpak

- name: Install Inkscape (Flatpak)
  flatpak:
    name: org.inkscape.Inkscape
    method: system
  tags:
    - flatpak

- name: Install LibreOffice (Flatpak)
  flatpak:
    name: org.libreoffice.LibreOffice
    method: system
  tags:
    - flatpak

- name: Install Lollypop (Flatpak)
  flatpak:
    name: org.gnome.Lollypop
    method: system
  tags:
    - flatpak

- name: Install Okular (Flatpak)
  flatpak:
    name: org.kde.okular
    method: system
  tags:
    - flatpak

- name: Install Seahorse (Flatpak)
  flatpak:
    name: org.gnome.seahorse.Application
    method: system
  tags:
    - flatpakp

- name: Install Spotify (Flatpak)
  flatpak:
    name: com.spotify.Client
    method: system
  tags:
    - flatpak

- name: Install Steam (Flatpak)
  flatpak:
    name: com.valvesoftware.Steam
    method: system
  tags:
    - flatpak

- name: Install Transmission (Flatpak)
  flatpak:
    name: com.transmissionbt.Transmission
    method: system
  tags:
    - flatpak

- name: Install VLC (Flatpak)
  flatpak:
    name: org.videolan.VLC
    method: system
  tags:
    - flatpak

- name: Install Zeal (Flatpak)
  flatpak:
    name: org.zealdocs.Zeal
    method: system
  tags:
    - flatpak

- name: Install Zoom (Flatpak)
  flatpak:
    name: us.zoom.Zoom
    method: system
  tags:
    - flatpak
