---

- name: Create repos directory
  file:
    path: "{{ ansible_env.HOME }}/repos"
    state: directory
    mode: '0755'

- name: Set up repositories
  include: repos.yml

- name: Install base packages
  include: packages.yml

- name: Install Flatpaks
  include: flatpak.yml

- name: Install dotfiles
  include: dotfiles.yml

- name: Install and configure Emacs
  include: emacs.yml

- name: Install/configure fonts
  include: fonts.yml

- name: Configure GNOME
  include: gnome.yml
