
- name: Update packages
  become: true
  dnf:
    name: "*"
    state: latest
  tags: dnf

- name: Install base packages
  become: yes
  dnf:
    name: "{{ base_packages }}"
    state: present
  tags:
    - dnf

- name: Install GUI packages
  become: yes
  dnf:
    name: "{{ gui_packages }}"
    state: present
  tags:
    - dnf
    - gui

- name: Install wine packages
  become: yes
  dnf:
    name: "{{ wine_packages }}"
    state: present
  tags:
    - dnf
    - wine

- name: Install audio encoding packages
  become: yes
  dnf:
    name: "{{ audio_encoding_packages }}"
    state: present
  tags:
    - dnf
    - audio

- name: Install RPMFusion multimedia group
  become: yes
  dnf:
    name: "@Multimedia"
    exclude: PackageKit-gstreamer-plugin
  tags:
    - dnf
    - rpmfusion
