
- name: Update packages
  become: true
  dnf:
    name: "*"
    state: latest
  tags: dnf

- name: Install base packages
  become: yes
  dnf:
    name: "{{ base_packages }}"
    state: present
  tags:
    - dnf

- name: Install RPMFusion multimedia group
  become: yes
  dnf:
    name: "@Multimedia"
    exclude: PackageKit-gstreamer-plugin
  tags:
    - dnf
    - rpmfusion
