---
# set up RPMFusion and any COPR repos needed

- name: Install RPMFusion free
  become: true
  dnf:
    name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  tags:
    - dnf
    - rpmfusion

- name: Install RPMFusion non-free
  become: true
  dnf:
    name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  tags:
    - dnf
    - rpmfusion

- name: Add dawid/better_fonts COPR
  become: true
  command:
    cmd: dnf copr enable -y dawid/better_fonts
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:dawid:better_fonts.repo
  tags:
    - dnf
    - copr
